title: Is there a chance to help reduce traffic crushes and save life in San Francisco?
description: A deep dive into the reasons and patterns behind the traffic crashes happened in San Francisco from 2005 to 2023.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
